version: 1.0.{build}
branches:
  only:
  - master
  
build_script:
- cmd: >-
    SET RUST_BACKTRACE=1
    
    cargo build --release
    
    cargo test --release
    
after_build:
- cmd: >-
   copy target\release\_3dtile.exe bin\3dtile.exe
   

artifacts:
  - path: bin
    name: 3dtiles
    
    
    
